---
# https://megalinter.io/latest/configuration/
DISABLE_ERRORS_LINTERS:
  - ACTION_ACTIONLINT
  - COPYPASTE_JSCPD
  - REPOSITORY_CHECKOV
  # - REPOSITORY_DEVSKIM
  # - REPOSITORY_DUSTILOCK
  # - REPOSITORY_GIT_DIFF
  - REPOSITORY_GITLEAKS
  # - REPOSITORY_SECRETLINT
  # - REPOSITORY_SYFT
  - REPOSITORY_TRIVY
  - SPELL_MISSPELL
  - SPELL_CSPELL
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TERRAFORM_FMT
  - TERRAFORM_CHECKOV
  - TERRAFORM_KICS
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - YAML_V8R
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - CSS_STYLELINT
  - CSS_SCSS_LINT
  - HTML_DJLINT
  - HTML_HTMLHINT
  - JAVASCRIPT_STANDARD

FILTER_REGEX_EXCLUDE: (themes/agico/layouts/)
